// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {alpaca} from '../models';
import {models} from '../models';
import {app} from '../models';
import {marketdata} from '../models';
import {options} from '../models';

export function GetAccount():Promise<alpaca.Account>;

export function GetAppData():Promise<models.AppData>;

export function GetAssets():Promise<Array<alpaca.Asset>>;

export function GetCandlesticks(arg1:app.GetCandlesticksConfig):Promise<Array<marketdata.Bar>>;

export function Logout():Promise<void>;

export function OnSecondInstanceLaunch(arg1:options.SecondInstanceData):Promise<void>;

export function ResetPreferences():Promise<void>;

export function SaveAppData(arg1:models.AppData):Promise<void>;

export function TestCredentials(arg1:string,arg2:string):Promise<boolean>;
