// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAccount() {
  return window['go']['app']['App']['GetAccount']();
}

export function GetAppData() {
  return window['go']['app']['App']['GetAppData']();
}

export function GetAssets() {
  return window['go']['app']['App']['GetAssets']();
}

export function GetCandlesticks(arg1) {
  return window['go']['app']['App']['GetCandlesticks'](arg1);
}

export function Logout() {
  return window['go']['app']['App']['Logout']();
}

export function OnSecondInstanceLaunch(arg1) {
  return window['go']['app']['App']['OnSecondInstanceLaunch'](arg1);
}

export function ResetPreferences() {
  return window['go']['app']['App']['ResetPreferences']();
}

export function SaveAppData(arg1) {
  return window['go']['app']['App']['SaveAppData'](arg1);
}

export function TestCredentials(arg1, arg2) {
  return window['go']['app']['App']['TestCredentials'](arg1, arg2);
}
