// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {persistence} from '../models';

export function Load():Promise<persistence.AppData>;

export function Ping():Promise<string>;

export function Save(arg1:persistence.AppData):Promise<void>;
