// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetProducts() {
  return window['go']['main']['App']['GetProducts']();
}

export function GetSystems() {
  return window['go']['main']['App']['GetSystems']();
}

export function LoadAppData() {
  return window['go']['main']['App']['LoadAppData']();
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function SaveAppData(arg1) {
  return window['go']['main']['App']['SaveAppData'](arg1);
}
