// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAccount() {
  return window['go']['main']['App']['GetAccount']();
}

export function GetAppData() {
  return window['go']['main']['App']['GetAppData']();
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function SaveAppData(arg1) {
  return window['go']['main']['App']['SaveAppData'](arg1);
}

export function TestCredentials(arg1, arg2) {
  return window['go']['main']['App']['TestCredentials'](arg1, arg2);
}
