// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {rti} from '../models';
import {persistence} from '../models';

export function GetProducts():Promise<Array<rti.ResponseProductCodes>>;

export function GetSystems():Promise<rti.ResponseRithmicSystemInfo>;

export function LoadAppData():Promise<persistence.AppData>;

export function Ping():Promise<string>;

export function SaveAppData(arg1:persistence.AppData):Promise<void>;
