name: Build and Deploy on Release

on:
  release:
    types: [created]


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/frontend:${{ github.event.release.tag_name }}
          cd frontend
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Configure kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Debug kubeconfig
        run: |
          echo "Kubeconfig content (without sensitive data):"
          kubectl config view --minify
          echo "Current context:"
          kubectl config current-context
          echo "Cluster info:"
          kubectl cluster-info

      - name: Test Kubernetes connection
        run: |
          kubectl version --client
          kubectl cluster-info
          kubectl get nodes

      - name: Update Kubernetes deployment
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/frontend:${{ github.event.release.tag_name }}
          kubectl set image deployment/delta-frontend delta=$IMAGE_NAME
          kubectl rollout status deployment/delta-frontend --timeout=120s
