name: Build and Deploy on Release

on:
  release:
    types: [created]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/frontend:${{ github.event.release.tag_name }}
          cd frontend
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Configure kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > $HOME/.kube/config

      - name: Update Kubernetes deployment
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}
          kubectl set image deployment/<votre-deployment> <votre-container>=$IMAGE_NAME
          kubectl rollout status deployment/<votre-deployment>
