name: Build and Deploy - Prod

on:
  release:
    types: [created]


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          LATEST_IMAGE_NAME=ghcr.io/${{ github.repository }}/frontend:latest
          TAGGED_IMAGE_NAME=ghcr.io/${{ github.repository }}/frontend:${{ github.event.release.tag_name }}
          cd frontend
          docker build -t $LATEST_IMAGE_NAME .
          docker build -t $TAGGED_IMAGE_NAME .
          docker push $LATEST_IMAGE_NAME
          docker push $TAGGED_IMAGE_NAME

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Configure kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Update Kubernetes deployment
        run: |
          kubectl -n delta rollout restart deployment/delta-frontend-prod --timeout=120s
